### ISSUE TITLE
作者太牛了，我也一直想做一个类似的东东，但是不知道怎么上手，牛逼！！

### ISSUE THREAD

**Issue by yiping2023** [HATTER-LONG/Verbiverse#20]
继续加油！！做大做强

**Comment by HATTER-LONG** [comment]
哈哈、过奖过奖。

如果有 QT 基础，界面相关开发可以参考[这篇文章](https://sspai.com/post/91090) ，LangChain 的话就推荐看官网的教程，在文章后半部分有链接。

欢迎提建议和 PR 🚀
