### ISSUE TITLE
很厉害，首先留下一个没意义的楼，以表示我的赞叹之情

### ISSUE THREAD

**Issue by UnWaitingGo** [HATTER-LONG/Verbiverse#21]
我发现在window上运行window版程序，window会限制运行，还要我手动解除。请问一下大大在这方面可以做些优化吗？当然我不知道怎么实现，单纯从使用者角度给出该建议（不痛不痒）。

**Comment by UnWaitingGo** [comment]
特别是作者的文档写的炒鸡详细，很适合大学生入手，做这么详细的文档，这~你受得了嘛~~~~
文档界面：https://sspai.com/post/91090
结合python构建客户端进行软件开发，着实不错。。期待作者开发一个RAG项目捏

**Comment by HATTER-LONG** [comment]
@UnWaitingGo 更新发布了 V1.1.1，我找了台 win11 试了下，你说的限制运行应该是加签验证导致的，直接继续运行就行，如果不放心安装包，可以自己 fork 下项目在 action 里重新打包，我这打包都是用的 action 所以加签名就没什么办法了

**Comment by UnWaitingGo** [comment]
HHH好的好的，我肯定是相信大佬的，今天偶然看到有频道发布了您的项目，所以就立即下载了试了一试，很有意思。请问大佬有微信嘛，能否加一个。。我是一枚小摆，今年大二，嘻嘻嘻！

________________________________
发件人: Layton ***@***.***>
发送时间: 2024年9月12日 13:47
收件人: HATTER-LONG/Verbiverse ***@***.***>
抄送: 行不止 ***@***.***>; Mention ***@***.***>
主题: Re: [HATTER-LONG/Verbiverse] 很厉害，首先留下一个没意义的楼，以表示我的赞叹之情 (Issue #21)


@UnWaitingGo<https://github.com/UnWaitingGo> 更新发布了 V1.1.1，我找了台 win11 试了下，你说的限制运行应该是加签验证导致的，直接继续运行就行，如果不放心安装包，可以自己 fork 下项目在 action 里重新打包，我这打包都是用的 action 所以加签名就没什么办法了

―

**Comment by HATTER-LONG** [comment]
微信号：`layton-logix`，也可以来加入 Discord，https://discord.gg/YRq2MMMn

**Comment by UnWaitingGo** [comment]
OK的OK的蟹蟹

________________________________
发件人: Layton ***@***.***>
发送时间: 2024年9月12日 14:35
收件人: HATTER-LONG/Verbiverse ***@***.***>
抄送: 行不止 ***@***.***>; Mention ***@***.***>
主题: Re: [HATTER-LONG/Verbiverse] 很厉害，首先留下一个没意义的楼，以表示我的赞叹之情 (Issue #21)


微信号：layton-logix，也可以来加入 Discord，https://discord.gg/YRq2MMMn

―
